### PR TITLE
Add a "Continuous conversation capability" to VA with the Box 3

### PR DESCRIPTION
**Pull request by jaymunro**
Initially adding this to the wake-word firmware with the hope to extend it to the non-micro_wake_word firmware.

Adding a switch `continuous_conversation` 
Adding logic to use `voice_assistant.start_continuous` in `micro_wake_word`

Will yet need to add a timeout to automatically drop back to listening for a wake word

### CODE REVIEW

**Comment by jaymunro** [comment]
It is working in testing but need to research on how to add a timeout in there somewhere.
Also, logic for stopping the continuous based on intent would be nice too.

**Comment by jaymunro** [comment]
belay that. an upgrade to esphome 2024.2.1 appears to have resolved the matter

**Comment by jaymunro** [comment]
92fbcee also adds ability to timeout back to idle (listening for wake word) when in continuous mode using a script in restart mode with a `wait` inside.

**Comment by jaymunro** [comment]
changed name to `continued_conversation` in line with Google Assistant terminology.

**Comment by ThreepE0** [comment]
I'm not sure how to tell, was there a pull request for this or no?

**Pull request closed without merging**
